### ISSUE TITLE
Upgrade to C++14

### ISSUE THREAD

**Issue by arximboldi** [AbletonAG/atria#17]
C++14 is widespread enough and even Visual Studio support it. In fact, the only reason the library can't be used in Visual Studio nowadays is expression sfinae, not C++14.

This involves removing some of the C++14 stuff from `estd`, `ABL_DECLTYPE_RETURN` and some other transition adaptors. It does not necessarily mean migrating all code to shorter C++14 idioms (e.g. transducers).

I would like to start working on this soon. RFC @toh-ableton @sbs-ableton

**Comment by toh-ableton** [comment]
Seems like a great idea to me

**Comment by mst-ableton** [comment]
Closing because this repository is currently unmaintained.
