### ISSUE TITLE
Split src/ directory

### ISSUE THREAD

**Issue by arximboldi** [AbletonAG/atria#18]
I would like to split the `src/` directory into `include/`, `src/` and `test/`.

Rationale: some of the library modules are header-only. It is hard to see what modules are header only and which not at the moment. By doing the split, one can easily see what modules are not header only by looking at the `src/` folder. Also, it makes writing packaging rules a bit easier, and it's easier for newcomers to find the tests.

RFC @toh-ableton @sbs-ableton

**Comment by sbs-ableton** [comment]
I think that's a good idea - reading through the code it made it a bit difficult to discern what the dependencies are (e.g. a lot of tests for lower level operations depend on `xform`, there is a circular dependency between `estd` and `meta`) and this would make that a lot clearer as well.

**Comment by arximboldi** [comment]
I see you are going deep in reviewing the code! This information about the dependencies is very valuable. We could take further steps to make that clear... e.g. add separate cmake files per module with different targets.

**Comment by sbs-ableton** [comment]
I've also pushed an RFC pull request for the dependency changes - let me know your thoughts :smile:

**Comment by mst-ableton** [comment]
Closing because this repository is currently unmaintained.
