### ISSUE TITLE
Help to find C++ transfer file send and recieve

### ISSUE THREAD

**Issue by swatians** [AbletonAG/atria#23]
Dear Sir,

I am looking C++ Transfer file send and recieve code source need your help. Thanks

Regards,
Ali

**Comment by toh-ableton** [comment]
Dear Ali, I'm not sure I understand your issue and how it is related to this project.

Best,
Tobias

**Comment by arximboldi** [comment]
I believe this issue was opened here by mistake. Closing for now.
