### ISSUE TITLE
CMake issues

### ISSUE THREAD

**Issue by compjuicer** [AbletonAG/atria#4]
Apparently, the latest Homebrew version of CMake (3.1.3) doesn't support the `set(CMAKE_CXX_STANDARD 11)` line in `CMakeLists.txt`, and the build throws various errors because of the missing `-std=c++11` flag:

```
CMake Error in CMakeLists.txt:
  Target "atria" requires the language dialect "CXX11" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.
```

In the end I could get Atria to compile by replacing the above line in CMakeLists.txt with the following:

```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```

For a better solution, I just installed the latest CMake 3.3.1 from http://www.cmake.org, and ran
`/Applications/CMake.app/Contents/bin/cmake .` in the **Atria** folder.

Maybe a minimum version of CMake should be listed as a dependency in the docs?

**Comment by ghost** [comment]
I'm using `homebrew` here and CMake version is 3.2.2 (maybe you need to update?)

Nonetheless I agree that requiring such a recent CMake version should be documented. I will update the README later. Thanks!

**Comment by compjuicer** [comment]
You're right, I did a `brew update` but at that point my cmake was `cmake31` for experimenting with the CXX11 flag, and never reinstalled the "normal" `cmake` package... :grimacing:
